type: grid
cards:
  - type: vertical-stack
    cards:
      - type: entities
        entities:
          - entity: input_datetime.hp_officejet_6962_this_period_start_date
          - entity: input_number.hp_officejet_6962_pages_at_month_start
          - entity: sensor.hp_officejet_6962_total_pages_printed
          - entity: input_number.hp_officejet_6962_free_pages_remaining_notification
          - entity: input_select.hp_officejet_6962_print_plan
          - entity: input_number.hp_officejet_6962_pages_monthly_allowance
          - entity: input_number.hp_officejet_6962_pages_rollover_allowance
          - entity: input_number.hp_officejet_6962_pages_rollover_monthly_max_allowance
          - entity: input_number.hp_officejet_6962_pages_overprint_block_size
          - entity: input_number.hp_officejet_6962_pages_overprint_block_cost
        title: HP OfficeJet 6962 Configuration
